### ISSUE TITLE
FountainEncoder.findNominalFragmentLength edge case issue

### ISSUE THREAD

**Issue by zhangjun725** [sparrowwallet/hummingbird#1]
**Description:**
when I call the constructor `public UREncoder(UR ur, int maxFragmentLen, int minFragmentLen, long firstSeqNum)`
if `minFragmentLen`  is smaller than `ur.getCborBytes().length`  exception occurs

**Exception stack**
```
Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:265)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
	at java.util.ArrayList.add(ArrayList.java:462)
	at com.sparrowwallet.hummingbird.fountain.FountainEncoder.partitionMessage(FountainEncoder.java:96)
	at com.sparrowwallet.hummingbird.fountain.FountainEncoder.<init>(FountainEncoder.java:45)
	at com.sparrowwallet.hummingbird.UREncoder.<init>(UREncoder.java:18)
	at com.sparrowwallet.hummingbird.URTest.testEncode(URTest.java:37)
```
**Test code:**
```
byte[] message = "Hello".getBytes();
UR ur = UR.fromBytes(message);
UREncoder urEncoder = new UREncoder(ur, 200, 100, 0);
```

**Comment by craigraw** [comment]
Thanks for the bug report, fixed in ee01cfc.

Let me know if you need a new minor release with this fix.

**Comment by zhangjun725** [comment]
Thanks.
In fact, I'm using the version compiled by myself with Java 8 in Android. Your release is built with Java15 and cannot be used directly in Android.

**Comment by craigraw** [comment]
Yes, this has been troubling me as well, since there was no good reason for Java 15.

I've made some changes and the project is now compiled on Java 8. There is a new 1.5.5 release which should be in Maven Central soon.

**Comment by zhangjun725** [comment]
Great, thank you very much🎉🎉🎉
